sudo: false

language: scala
scala:
  - 2.12.11
  - 2.13.1

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13

install: true

script:
  - java -version
  - sbt test

