sudo: false

language: scala
scala:
  - 2.12.15
  - 2.13.7
  - 3.0.2
  - 3.1.0

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk11
  - oraclejdk17

install: true

script:
  - java -version
  - sbt test

